{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: chorus-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "i2b2-frontend.labels" . | nindent 4 }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: {{ .Values.gateway.namespace }}
  to:
    - group: ""
      kind: Service
{{- end }}
