apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mycaddy
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: registry.gpu1.thehip.app
    chart: charts/caddy-ingress-controller
    targetRevision: 0.0.1
  destination:
    server: https://kubernetes.default.svc
    namespace: caddy-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
