apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-registry
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CHUV-DIP/horus.git
    path: charts/docker-registry
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
