apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: registry.gpu1.thehip.app
    chart: registry
    targetRevision: 0.0.1
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
