apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xpra-server
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CHUV-DIP/horus.git
    path: charts/xpra-server
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
