apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xpra-server
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/chuv-dip
    chart: xpra-server
    targetRevision: 0.0.1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
