version: 2.1
jobs:
  lint:
    docker:
    - image: twuni/helm:3.5.2
    steps:
    - checkout
    - run:
        command: helm lint --strict
        name: lint
workflows:
  version: 2
  default:
    jobs:
    - lint
