docker-registry:
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: caddy
    hosts:
      - registry.horus-build.thehip.app
    path: /
    tls: []
  persistence:
    enabled: true
    deleteEnabled: true
    existingClaim: registry-pv-claim
  env:
    - name: REGISTRY_AUTH
      valueFrom:
        secretKeyRef:
          name: registry-htpasswd
          key: htpasswd
