{{- $fullName := include "chorus-ci.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-github-eventsource-svc
  labels:
    {{- include "chorus-ci.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    eventsource-name: {{ $fullName }}-github
  type: {{ .Values.service.type }}
