apiVersion: v2
description: Backup and disaster recovery solution for Kubernetes clusters
name: velero
version: 0.0.2
dependencies:
  - name: velero
    version: 11.4.0
    repository: https://vmware-tanzu.github.io/helm-charts

maintainers:
  - name: idmple
    email: nathalie.casati@chuv.ch
  - name: johaab
    email: jonathan.haab@chuv.ch
