apiVersion: v2
description: The Helm chart for Envoy Gateway
name: gateway-helm
version: 0.0.7
dependencies:
  - name: gateway-helm
    version: v1.4.1
    repository: oci://docker.io/envoyproxy

maintainers:
  - name: iDmple
    email: nathalie.casati@chuv.ch
