{{- $fullName := include "argo-ci.fullname" . -}}
{{- $serviceAccountName := include "argo-ci.serviceAccountName" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ $fullName }}-build-workbench-operator
spec:
  eventBusName: {{ $fullName }}-default
  template:
    serviceAccountName: {{ $serviceAccountName }}
  dependencies:
    - name: build-workbench-operator
      eventSourceName: {{ $fullName }}-github
      eventName: workbench-operator
      filters:
        data:
          - path: "body.ref"
            type: string
            value:
              # The goal is to publish tagged releases.
              #- "refs/heads/master"
              - "refs/tags/v*"

  triggers:
    - template:
        name: github-workflow-trigger-workbench-operator
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: "-"
              spec:
                serviceAccountName: {{ $serviceAccountName }}
                entrypoint: build-workbench-operator
                volumes:
                  - name: docker-config
                    secret:
                      secretName: {{ .Values.sensor.dockerConfig.secretName | quote }}
                      items:
                        - key: .dockerconfigjson
                          path: config.json
                arguments:
                  parameters:
                    - name: repo-url
                    - name: revision
                    - name: ref
                    - name: commitId
                    - name: tag
                templates:
                  - name: build-workbench-operator
                    steps:
                      - - name: docker-build
                          templateRef:
                            name: docker-build-template
                            template: docker-build
                          arguments:
                            parameters:
                              - name: registry
                                value: {{ .Values.sensor.registry | quote }}
                              - name: image
                                value: "workbench-operator"
                              - name: tag
                                value: "{{`{{workflow.parameters.tag}}`}}"
                              - name: commitId
                                value: "{{`{{workflow.parameters.commitId}}`}}"
                              - name: dockerfile
                                value: "Dockerfile"
                            artifacts:
                              - name: source
                                git:
                                  repo: "{{`{{workflow.parameters.repo-url}}`}}"
                                  revision: "{{`{{workflow.parameters.revision}}`}}"
                                  usernameSecret:
                                    name: argo-workflows-github-workbench-operator
                                    key: username
                                  passwordSecret:
                                    name: argo-workflows-github-workbench-operator
                                    key: password
                                  depth: 1
                                  ref: "{{`{{workflow.parameters.ref}}`}}"

                      - - name: oci-credentials
                          template: oci-credentials

                      - - name: helm-build
                          template: helm-build
                          arguments:
                            parameters:
                              - name: oci-username
                                value: "{{`{{ steps.oci-credentials.outputs.parameters.username }}`}}"
                              - name: oci-password
                                value: "{{`{{ steps.oci-credentials.outputs.parameters.password }}`}}"

                  - name: oci-credentials
                    container:
                      image: backplane/jq
                      volumeMounts:
                        - name: docker-config
                          mountPath: /.docker
                      env:
                        - name: DOCKER_CONFIG
                          value: /.docker
                        - name: REGISTRY
                          value: {{ .Values.sensor.registry | quote }}
                      command: [sh, -c]
                      args:
                        - >-
                          auth="$(cat "${DOCKER_CONFIG}/config.json" | jq -r ".auths.\"${REGISTRY}\".auth")";
                          echo "${auth}" | base64 -d | awk -F: '{ print $1 }' > /tmp/username;
                          echo "${auth}" | base64 -d | awk -F: '{ print $2 }' | base64 > /tmp/password
                    outputs:
                      parameters:
                        - name: username
                          valueFrom:
                            path: /tmp/username
                        - name: password
                          valueFrom:
                            path: /tmp/password

                  - name: helm-build
                    inputs:
                      # FIXME: we need artifact storage to pass the password as a file.
                      parameters:
                        - name: oci-username
                        - name: oci-password
                      artifacts:
                        - name: images
                          path: "/src"
                          git:
                            repo: "{{`{{workflow.parameters.repo-url}}`}}"
                            revision: "{{`{{workflow.parameters.revision}}`}}"
                            usernameSecret:
                              name: argo-workflows-github-workbench-operator
                              key: username
                            passwordSecret:
                              name: argo-workflows-github-workbench-operator
                              key: password
                            depth: 1
                            ref: "{{`{{workflow.parameters.ref}}`}}"
                    container:
                      image: alpine/helm
                      env:
                        - name: REGISTRY
                          value: {{ .Values.sensor.registry | quote }}
                      command: [sh, -e, -c]
                      args:
                        - >-
                          helm package charts/workbench-operator;
                          echo -n "{{`{{inputs.parameters.oci-password}}`}}" | tee /tmp/password
                          cat /tmp/password | base64 -d | helm registry login -u "{{`{{inputs.parameters.oci-username}}`}}" --password-stdin  "${REGISTRY}";
                          helm push workbench-operator-*.tgz "oci://${REGISTRY}/charts";
                      workingDir: "/src"

          parameters:
            - src:
                dependencyName: build-workbench-operator
                dataKey: body.repository.clone_url
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: build-workbench-operator
                dataKey: body.after
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: build-workbench-operator
                dataKey: body.ref
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: build-workbench-operator
                dataTemplate: "{{`{{ .Input.body.head_commit.id | substr 0 7 }}`}}"
              dest: spec.arguments.parameters.3.value
            - src:
                dependencyName: build-workbench-operator
                dataTemplate: '{{`{{ if hasPrefix "refs/tags/v" .Input.body.ref }}{{ .Input.body.ref | trimPrefix "refs/tags/v"  }}{{ else }}n/a{{ end }}`}}'
              dest: spec.arguments.parameters.4.value
            # Append text and commit id to dynamically assign workflow name.
            - src:
                dependencyName: build-workbench-operator
                dataTemplate: "build-workbench-operator-{{`{{ .Input.body.head_commit.id | substr 0 7 }}`}}"
              dest: metadata.generateName
              operation: prepend
      retryStrategy:
        steps: 3
