{{- $fullName := include "argo-ci.fullname" . -}}
{{- $serviceAccountName := include "argo-ci.serviceAccountName" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ $fullName }}-build-web-ui
spec:
  eventBusName: {{ $fullName }}-default
  template:
    serviceAccountName: {{ $serviceAccountName }}
  dependencies:
    - name: build-web-ui
      eventSourceName: github
      eventName: chorus-web-ui
      filters:
        data:
          - path: "body.ref"
            type: string
            value:
              - "refs/heads/main"

  triggers:
    - template:
        name: github-workflow-trigger-web-ui
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: "-"
              spec:
                serviceAccountName: {{ $serviceAccountName }}
                entrypoint: build-images
                arguments:
                  parameters:
                    - name: repo-url
                    - name: revision
                    - name: ref
                    - name: commit_id
                templates:
                  - name: build-images
                    steps:
                      - - name: docker-build
                          template: docker-build

                  - name: docker-build
                    inputs:
                      artifacts:
                        - name: images
                          path: "/src"
                          git:
                            repo: "{{`{{workflow.parameters.repo-url}}`}}"
                            revision: "{{`{{workflow.parameters.revision}}`}}"
                            usernameSecret:
                              name: argo-workflows-github-images
                              key: username
                            passwordSecret:
                              name: argo-workflows-github-images
                              key: password
                            depth: 1
                            ref: "{{`{{workflow.parameters.ref}}`}}"
                    container:
                      image: docker:26
                      env:
                        - name: DOCKER_HOST
                          value: 127.0.0.1
                        - name: REGISTRY
                          value: {{ .Values.sensor.registry | quote }}
                      command: [sh, -c]
                      args:
                        - >-
                          until docker ps;
                            do sleep 3;
                          done;

                          VERSION="$(date +%Y%m%d)-{{`{{workflow.parameters.commit_id}}`}}"

                          docker buildx build
                          --pull
                          --tag "${REGISTRY}/chorus-web-ui:${VERSION}"
                          --output "type=registry"
                          .
                      workingDir: "/src"
                    sidecars:
                      - name: dind
                        image: docker:26-dind
                        env:
                          - name: DOCKER_TLS_CERTDIR
                            value: ""
                        securityContext:
                          privileged: true
                        mirrorVolumeMounts: true

          parameters:
            - src:
                dependencyName: build-images
                dataKey: body.repository.clone_url
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: build-images
                dataKey: body.after
              dest: spec.arguments.parameters.1.value
            - src:
                dependencyName: build-images
                dataKey: body.ref
              dest: spec.arguments.parameters.2.value
            - src:
                dependencyName: build-images
                dataTemplate: "{{`{{ .Input.body.head_commit.id | substr 0 7 }}`}}"
              dest: spec.arguments.parameters.3.value
            # Append text and commit id to dynamically assign workflow name.
            - src:
                dependencyName: build-images
                dataTemplate: "build-web-ui-{{`{{ .Input.body.head_commit.id | substr 0 7 }}`}}"
              dest: metadata.generateName
              operation: prepend
      retryStrategy:
        steps: 3
