{{- $fullName := include "argo-ci.fullname" . -}}
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ $fullName }}-docker-build-template
  labels:
    {{- include "argo-ci.labels" . | nindent 4 }}
spec:
  arguments:
    artifacts:
      - name: source
    parameters:
      - name: tag
        value: "n/a"
      - name: sha
      - name: dockerfile
        value: "Dockerfile"
      - name: image
      - name: registry
        value: "registry.build.chorus-tre.local"
      - name: dockerConfigSecret

  templates:
  - name: docker-build
    inputs:
      parameters:
        - name: tag
        - name: sha
        - name: dockerfile
        - name: image
        - name: registry
        - name: dockerConfigSecret
      artifacts:
        - name: source
          path: "/src"

    volumes:
      - name: docker-config
        secret:
          secretName: "{{`{{inputs.parameters.dockerConfigSecret}}`}}"
          items:
            - key: .dockerconfigjson
              path: config.json

    container:
      image: "docker:27"
      volumeMounts:
        - name: docker-config
          mountPath: /.docker
      env:
          # Otherwise buildx uses DOCKER_CONFIG for it, which is read-only.
        - name: BUILDX_CONFIG
          value: /tmp/buildx
        - name: DOCKER_CONFIG
          value: /.docker
        - name: DOCKER_HOST
          value: 127.0.0.1
        - name: DOCKERFILE
          value: "{{`{{inputs.parameters.dockerfile}}`}}"
        - name: REGISTRY
          value: "{{`{{inputs.parameters.registry}}`}}"
        - name: SHA
          value: "{{`{{inputs.parameters.sha}}`}}"
        - name: IMAGE
          value: "{{`{{inputs.parameters.image}}`}}"
        - name: TAG
          value: "{{`{{inputs.parameters.tag}}`}}"
      command: [sh, -e, -c]
      args:
        - >-
          until docker ps;
            do sleep 3;
          done;

          if [ -n "${TAG}" ] && [ "n/a" != "${TAG}" ]; then
            version="${TAG}";
          else
            version="$(date +%Y%m%d)-$(echo -n ${SHA} | cut -c 1-8)";
          fi;

          tag="${REGISTRY}/${IMAGE}:${version}";

          docker buildx build
          --pull
          --file "${DOCKERFILE}"
          --label "org.opencontainers.image.revision=${SHA}"
          --tag "${tag}"
          --output "type=registry"
          .
      workingDir: "/src"
    sidecars:
      - name: dind
        image: "docker:27-dind"
        env:
          - name: DOCKER_TLS_CERTDIR
            value: ""
        securityContext:
          privileged: true
        mirrorVolumeMounts: true
