docker-registry:
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: caddy
    hosts:
      - registry.horus-build.thehip.app
    path: /
    tls: []
  persistence:
    type: pvc
    enabled: true
    deleteEnabled: true
    #existingClaim: registry-pv-claim
    size: 500Gi
  extraContainers: []
    # Additional containers to be added
  # Use StatefulSet instead of Deployment. Default uses Deployment.
  useStatefulSet: true
  env:
    - name: REGISTRY_AUTH
      valueFrom:
        secretKeyRef:
          name: registry-htpasswd
          key: htpasswd
