# Default values for xpra-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: xpra-server
image:
  repository: registry.build.chorus-tre.local/xpra-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.0.1"
env:
  card: none
  xpraKeycloakAuth: false
