# Default values for workbench.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.build.chorus-tre.local/xpra-server
  pullPolicy: IfNotPresent
env:
  card: "none"
  xpraKeycloakAuth: "False" # True or False as a string in PascalCase
  xpraKeycloakServerUrl: ""
  xpraKeycloakRealmName: ""
  xpraKeycloakClientId: ""
  xpraKeycloakClientSecretKey: ""
  xpraKeycloakRedirectUri: ""
  xpraKeycloakScope: ""
  xpraKeycloakClaimField: "roles.groups"
  xpraKeycloakAuthGroups: ""
  xpraKeycloakAuthCondition: "and"
  xpraKeycloakGrantType: "authorization_code"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080 # container port
  targetPort: 8080 # pod port
  x11Port: 6080
  x11TargetPort: 6080

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx" # keeping this for testing purpose with colima, deprecated
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
  - host: workbench.chorus-tre.local
    paths:
      - path: /
        pathType: Prefix
  tls:
  - hosts:
    - workbench.chorus-tre.local
    secretName: workbench-tls

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false

# Additional volumes on the output Deployment definition.
volumes:
  - name: x11-socket
    emptyDir: {}

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: x11-socket
    mountPath: /tmp/.X11-unix

nodeSelector: {}

tolerations: []

affinity: {}
