{{- if and (.Values.networkPolicy.enabled) (eq .Values.networkPolicy.flavor "kubernetes") }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "loki.name" . }}-namespace-only
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "networkPolicy.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector:
    matchLabels:
      {{- include "loki.selectorLabels" . | nindent 6 }}
  egress:
    - to:
        - podSelector: {}
  ingress:
    - from:
        - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "loki.name" . }}-egress-dns
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "networkPolicy.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      {{- include "loki.selectorLabels" . | nindent 6 }}
  egress:
    - ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
      to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "loki.name" . }}-ingress
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "networkPolicy.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - gateway
    matchLabels:
      {{- include "loki.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        - port: {{ .Values.loki.gateway.containerPort | default "http" | quote }}
          protocol: TCP
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.fluentBit.namespace | default "fluent" }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: fluent-bit
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.kubePrometheusStack.namespace | default "prometheus" }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: grafana
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "loki.name" . }}-ingress-metrics
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "networkPolicy.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      {{- include "loki.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
        - port: http-metrics
          protocol: TCP
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.kubePrometheusStack.namespace | default "prometheus" }}
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
{{- if (gt (len .Values.networkPolicy.externalStorage.cidrs) 0) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "loki.name" . }}-egress-external-storage
  namespace: {{ include "loki.namespace" . }}
  labels:
    {{- include "networkPolicy.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      {{- include "loki.selectorLabels" . | nindent 6 }}
  egress:
    - ports:
        - port: "443"
          protocol: TCP
      to:
      {{- range $cidr := .Values.networkPolicy.externalStorage.cidrs }}
        - ipBlock:
            cidr: {{ $cidr }}
      {{- end }}
{{- end }}
{{- end }}
