{{- if .Values.allowedIngressNamespaces }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: keycloak-ingress-restrict
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  ingress:
    - fromEndpoints:
        {{- range .Values.allowedIngressNamespaces }}
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {{ . | quote }}
        {{- end }}
{{- end }}
