mariadb:
  auth:
    existingSecret: "mariadb-secret"
  primary:
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
