# Custom Chorus NetworkPolicy configuration
chorusNetworkPolicy:
  enabled: true
  enabled_l7_waf: false
  # Default ingress: Allow from same namespace only
  ingress: []
  # Default egress: Deny all (databases don't initiate outbound connections)
  egress: []

mariadb:
  image:
    repository: bitnamilegacy/mariadb
  global:
    security:
      allowInsecureImages: true
  auth:
    existingSecret: "mariadb-secret"
  # Disable Bitnami's NetworkPolicy (we use custom Chorus NetworkPolicy templates)
  networkPolicy:
    enabled: false
  primary:
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
  metrics:
    enabled: false
    image: 
      repository: bitnamilegacy/mysqld-exporter
    serviceMonitor:
      enabled: false
    extraArgs:
      primary:
        - --collect.global_status
        - --collect.global_variables
        - --collect.info_schema.query_response_time
        - --no-collect.slave_status
        - --no-collect.info_schema.innodb_cmp
        - --no-collect.info_schema.innodb_cmpmem
  tls:
    enabled: false
    autoGenerated:
      enabled: true
      engine: cert-manager
      certManager:
        existingIssuer: CHANGEME-issuer
        existingIssuerKind: ClusterIssuer
