mariadb:
  auth:
    existingSecret: "mariadb-secret"
  primary:
    livenessProbe:
      timeoutSeconds: 10
    readinessProbe:
      timeoutSeconds: 10
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  tls:
    enabled: false
    # Generate this secret using a cert-manager Certificate resource.
    existingSecret: mariadb-general-tls
    certFilename: "tls.crt"
    certKeyFilename: "tls.key"
    # Set this up to enforce the client certificate verification.
    certCAFilename: ""

certificate:
  enabled: false

  # Same as above.
  secretName: mariadb-general-tls

  duration: 2169h # 90d
  renewBefore: 360h # 15d

  issuerRef:
    name: CHANGEME-issuer
