
apiVersion: v1
kind: Pod
metadata:
  name: test-harbor-pull
  namespace: harbor
spec:
  containers:
  - name: busybox
    image: harbor-core.local/docker_proxy/library/busybox:stable
    command: ['sh', '-c', 'echo "Image pull successful!" && sleep 3600']
  imagePullSecrets:
  - name: regcred
  restartPolicy: Never
