apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: chorus-gateway
  namespace: envoy-gateway-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: eg
  listeners:
    - name: https
      port: 443
      protocol: HTTPS
      hostname: {{ .Values.tls.hostname | quote }}
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.tls.secretName | quote }}
      allowedRoutes:
        namespaces:
          from: All
