{{- if and .Values.chorusNetworkPolicy.enabled (not .Values.chorusNetworkPolicy.enabled_l7_waf) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-postgresql-chorus
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: i2b2-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: i2b2-postgres
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Default: Allow ingress from same namespace only on PostgreSQL port
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace | quote }}
    ports:
    - protocol: TCP
      port: 5432
  {{- with .Values.chorusNetworkPolicy.ingress }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  egress: [] # Deny all egress for database (empty array = no rules)
{{- end }}

