apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chorusapp.fullname" . }}
  labels:
    {{- include "chorusapp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "chorusapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chorusapp.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CARD
              value: "{{ .Values.env.card }}"
            - name: APP_NAME
              value: "{{ .Values.env.app_name }}"
            - name: DISPLAY
              value: "{{ .Values.env.display }}"
