apiVersion: v2
description: Web-based Git-repository manager with wiki and issue-tracking features.
name: gitlab
version: 0.0.6
dependencies:
  - name: gitlab
    version: 9.9.3
    repository: https://charts.gitlab.io

maintainers:
  - name: iDmple
    email: nathalie.casati@chuv.ch
