apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: horus
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: 'https://github.com/CHUV-DIP/horus.git'
      revision: HEAD
      files:
      - path: "environments/*/*/config.json"
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{.path.basename}}'
      annotations:
        '{{.images}}'
    spec:
      project: default
      sources:
      - repoURL: 'registry.gpu1.thehip.app'
        chart: '{{.chart}}'  # Take chart from config.json
        targetRevision: '{{.version}}'  # Take version from config.json
        helm:
          valueFiles:
          - $values/environments/{{index .path.segments 1}}/{{.path.basename}}/values.yaml
      - repoURL: 'https://github.com/CHUV-DIP/horus.git'
        targetRevision: HEAD
        ref: values

      destination:
        name: '{{.cluster}}'
        namespace: '{{.namespace}}'  # Take namespace from config.json
      syncPolicy:
        automated:
          prune: true  # Optionally enable pruning for resources not defined in Git
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - preserveResourcesOnDeletion=true
