apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chorus
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: 'https://github.com/<YOUR-ORG>/environments-template.git'
      revision: HEAD
      files:
      - path: "*/*/config.json"
  template:
    metadata:
      name: '{{index .path.segments 0}}-{{.path.basename}}'
      #annotations:
      #  argocd-image-updater.argoproj.io/image-list: '{{.images}}'
    spec:
      project: default
      sources:
      - repoURL: 'registry.build.chorus-tre.local'
        chart: '{{.chart}}'  # Take chart from config.json
        targetRevision: '{{.version}}'  # Take version from config.json
        helm:
          valueFiles:
          - $values/{{index .path.segments 0}}/{{.path.basename}}/values.yaml
      - repoURL: 'https://github.com/<YOUR-ORG>/environments-template.git'
        targetRevision: HEAD
        ref: values

      destination:
        name: '{{.cluster}}'
        namespace: '{{.namespace}}'  # Take namespace from config.json
      syncPolicy:
        automated:
          prune: true  # Optionally enable pruning for resources not defined in Git
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - preserveResourcesOnDeletion=true
