# Default values for argo-ci.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

sensor:
  # Where the OCI images built by the sensor are pushed to.
  registry: harbor.build.chorus-tre.local
  # This secret shall be of type kubernetes.io/dockerconfigjson
  dockerConfig:
    secretName: registry-dockerconfigjson-secret

# Creates the webhook and matching events on the GibHub EventSource.
webhookEvents:
  - name: ci
    repositories:
      - owner: chorus-tre
        names:
          - images

    # That secret must contain the following keys:
    # - token (a GitHub pat), and secret (the webhook secret).
    secretName: argo-ci-github-images

  - name: chorus-web-ui
    repositories:
      - owner: chorus-tre
        names:
          - chorus-web-ui
    secretName: argo-ci-github-chorus-web-ui

  - name: chorus-backend
    repositories:
      - owner: chorus-tre
        names:
          - chorus-backend
    secretName: argo-ci-github-chorus-backend

githubSecrets:
  chorus-backend: argo-workflows-github-chorus-backend
  chorus-web-ui: argo-workflows-github-chorus-web-ui
  workbench-operator: argo-workflows-github-workbench-operator

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080
  targetPort: 12000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/app-root: /push
  hosts:
    - host: webhook-ci.build.chorus-tre.local
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - hosts:
        - webhook-ci.build.chorus-tre.local
      secretName: argo-ci-tls

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
