{{- $name := include "self-signed-ca.name" . }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}-ca
  labels:
    {{- include "self-signed-ca.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: {{ $name }}-ca
  secretName: {{ $name }}-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    {{- if .Values.root.global }}
    name: {{ $name }}-cluster-issuer
    kind: ClusterIssuer
    {{- else }}
    name: {{ $name }}-issuer
    kind: Issuer
    {{- end }}
    group: cert-manager.io
