apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: chorus-build
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "CHORUS build cluster"
  sourceRepos:
    - "*"
  # Only self is allowed
  destinations:
    - name: "chorus-build"
      namespace: "*"
      server: "https://kubernetes.default.svc"
  permitOnlyProjectScopedClusters: true

  clusterResourceBlacklist: []
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist: []
  namespaceResourceWhitelist: []
