apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: chorus-sck
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "CHORUS SCK"
  sourceRepos:
    - "*"
  # Only self is allowed
  destinations:
    - name: "chorus-sck"
      namespace: "*"
  permitOnlyProjectScopedClusters: false

  clusterResourceBlacklist: []
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceBlacklist: []
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
