registry-ui:
  ui:
    title: "CHORUS OCI registry"
    dockerRegistryUrl: registry.horus-build.thehip.app
    registrySecured: true
    ingress:
      enabled: true
      host: registry-ui.horus-build.thehip.app
      ingressClassName: ""
      annotations:                                       
        kubernetes.io/ingress.class: caddy
