docker-registry-ui:
  ui:
    image: joxit/docker-registry-ui:2.5.7
    title: "CHORUS OCI registry"
    dockerRegistryUrl: "https://registry.build.chorus-tre.local"
    registrySecured: true
    ingress:
      enabled: true
      host: registry-ui.build.chorus-tre.local
      ingressClassName: "nginx"
      annotations:                                       
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
      - hosts:
        - registry-ui.build.chorus-tre.local
        secretName: registry-ui-tls
    proxy: false
    useControlCacheHeader: true
    nginxProxyHeaders: [{'Access-Control-Allow-Credentials': '"true"'}, { 'Access-Control-Allow-Origin': 'https://registry.build.chorus-tre.local' }]
