docker-registry-ui:
  ui:
    title: "CHORUS OCI registry"
    dockerRegistryUrl: "https://registry.build.chorus-tre.local"
    registrySecured: false
    ingress:
      enabled: true
      host: registry-ui.build.chorus-tre.local
      ingressClassName: ""
      annotations:                                       
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        - hosts:
          - registry-ui.build.chorus-tre.local
          secretName: registry-registry-ui-tls
    proxy: false
    useControlCacheHeader: true
    nginxProxyHeaders: [{'Access-Control-Allow-Credentials': '"true"'}, { 'Access-Control-Allow-Origin': 'https://registry.build.chorus-tre.local' }]
