docker-registry:
  secrets:
    htpasswd: registry-htpasswd
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: caddy
    hosts:
      - registry.gpu1.thehip.app
    path: /
    tls: []
