{{- $currentScope := . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-realm-config" .Release.Name | quote }}
  namespace: {{ $currentScope.Release.Namespace }}
data:
{{- range $path, $_ := .Files.Glob "files/realm/*-realm.yaml" }}
  {{- $rendered := tpl (.Files.Get $path) $currentScope | trim }}
  {{- if $rendered }}
  {{ base $path }}: |-
{{ $rendered | nindent 4 }}
  {{- end }}
{{- end }}
