apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: chorus-build-t
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: "https://github.com/CHORUS-TRE/environments.git"
        revision: feat/helm-chart-install # TODO: replace with "HEAD"
        files:
          - path: "chorus-build-t/*/config.json"
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: stepName
              operator: In
              values:
                - infrastructure
        - matchExpressions:
            - key: stepName
              operator: In
              values:
                - database
          maxUpdate: 20% # don't break them all at once.
        - matchExpressions:
            - key: stepName
              operator: In
              values:
                - application
          maxUpdate: 20% # don't break them all at once
  template:
    metadata:
      name: "{{index .path.segments 0}}-{{.path.basename}}"
      labels:
        stepName: '{{ if hasKey . "stepName" }}{{ .stepName }}{{ else }}application{{ end }}'
    spec:
      project: chorus-build-t
      sources:
        - repoURL: "harbor.build-t.chorus-tre.ch"
          chart: 'charts/{{ trimPrefix "charts/" .chart }}'
          targetRevision: "{{.version}}" # Take version from config.json
          helm:
            valueFiles:
              - $values/{{index .path.segments 0}}/{{.path.basename}}/values.yaml
        - repoURL: "https://github.com/CHORUS-TRE/environments.git"
          targetRevision: feat/helm-chart-install # TODO: replace with "HEAD"
          ref: values

      destination:
        name: chorus-build-t
        namespace: "{{.namespace}}" # Take namespace from config.json
      syncPolicy:
        automated:
          prune: true # Optionally enable pruning for resources not defined in Git
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - preserveResourcesOnDeletion=true
          - 'ServerSideApply={{if hasKey . "serverSideApply" }}{{ .serverSideApply }}{{ else }}false{{ end }}'
