apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: harbor-ingress-restrict
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  endpointSelector:
    matchLabels:
      app: harbor
  {{- if .Values.allowedIngressNamespaces }}
  ingress:
    - fromEndpoints:
        {{- range .Values.allowedIngressNamespaces }}
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: {{ . | quote }}
        {{- end }}
  {{- else }}
  ingress: []
  {{- end }}
