matomo:
  image:
    repository: bitnamilegacy/matomo
  global:
    security:
      allowInsecureImages: true
  matomoUsername: chorus
  matomoWebsiteName: chorus
  matomoWebsiteHost: https://matomo.chorus-tre.local
  existingSecret: "matomo-matomo-secret"
  allowEmptyPassword: false
  updateStrategy:
    type: Recreate
  ingress:
    enabled: false
  service:
    type: ClusterIP
  mariadb:
    enabled: false
  externalDatabase:
    host: "chorus-matomo-mariadb"
    port: 3306
    user: bn_matomo
    password: ""
    database: bitnami_matomo
    existingSecret: "matomo-mariadb-secret"
  cronjobs:
    archive:
      enabled: true
      persistence:
        enabled: true
        existingClaim: "matomo-archive"
    taskScheduler:
      enabled: true
      persistence:
        enabled: true
        existingClaim: "matomo-taskscheduler"
  priorityClassName: low-priority
