matomo:
  matomoUsername: chorus
  matomoWebsiteName: chorus
  matomoWebsiteHost: https://matomo.chorus-tre.local
  existingSecret: "matomo-matomo-secret"
  allowEmptyPassword: false
  updateStrategy:
    type: Recreate
  ingress:
    enabled: true
    pathType: Prefix
    ingressClassName: "nginx"
    hostname: "matomo.chorus-tre.local"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    tls: true
    selfSigned: false
  mariadb:
    enabled: false
  externalDatabase:
    host: "chorus-matomo-mariadb"
    port: 3306
    user: bn_matomo
    password: ""
    database: bitnami_matomo
    existingSecret: "matomo-mariadb-secret"
  cronjobs:
    archive:
      enabled: true
      persistence:
        enabled: true
        existingClaim: "matomo-archive"
    taskScheduler:
      enabled: true
      persistence:
        enabled: true
        existingClaim: "matomo-taskscheduler"
