{{- if and .Values.networkPolicy.enabled (not .Values.networkPolicy.enabled_l7_waf) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "didata.fullname" . }}-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "didata.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "didata.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- if .Values.networkPolicy.ingress }}
  {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- else }}
  # Default Deny Ingress: Empty ingress list means deny all unless explicitly allowed
  [] 
  {{- end }}
  egress:
  {{- if .Values.networkPolicy.egress }}
  {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
  # Default Deny Egress: Empty egress list means deny all unless explicitly allowed
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53 # Allow DNS resolution to kube-system
    - protocol: TCP
      port: 53 # Allow DNS resolution to kube-system
{{- end }}
