apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: didata-logs-pvc
  namespace: didata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: didata-user-storage-pvc
  namespace: didata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
