apiVersion: v2
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argo-cd
version: 0.0.11
dependencies:
  - name: argo-cd
    version: 7.2.1
    repository: https://argoproj.github.io/argo-helm
