apiVersion: v2
name: argo-cd
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
version: 0.0.32
dependencies:
  - name: argo-cd
    version: 8.2.0
    repository: https://argoproj.github.io/argo-helm

maintainers:
  - name: iDmple
    email: nathalie.casati@chuv.ch
  - name: floriansipp
    email: florian.sipp@chuv.ch
