apiVersion: v2
name: argo-cd
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
appVersion: v2.13.2
version: 0.0.31
dependencies:
  - name: argo-cd
    version: 7.7.10
    repository: https://argoproj.github.io/argo-helm

maintainers:
  - name: iDmple
    email: nathalie.casati@chuv.ch
  - name: floriansipp
    email: florian.sipp@chuv.ch
