{{- if .Values.matomo.cronjobs.archive.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-archive
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
{{- end }}
{{- if .Values.matomo.cronjobs.taskScheduler.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matomo-taskscheduler
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
{{- end }}
