apiVersion: v2
name: chorus-gateway
description: Envoy Gateway HTTPRoutes and SecurityPolicies for internal CHORUS services
version: 0.0.8
maintainers:
  - name: iDmple
    email: nathalie.casati@chuv.ch
