apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workbench.fullname" . }}
  labels:
    {{- include "workbench.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "workbench.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "workbench.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "workbench.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CARD
              value: "{{ .Values.env.card }}"
            - name: XPRA_KEYCLOAK_AUTH
              value: "{{ .Values.env.xpraKeycloakAuth }}"
            - name: XPRA_KEYCLOAK_SERVER_URL
              value: "{{ .Values.env.xpraKeycloakServerUrl }}"
            - name: XPRA_KEYCLOAK_REALM_NAME
              value: "{{ .Values.env.xpraKeycloakRealmName }}"
            - name: XPRA_KEYCLOAK_CLIENT_ID
              value: "{{ .Values.env.xpraKeycloakClientId }}"
            - name: XPRA_KEYCLOAK_CLIENT_SECRET_KEY
              value: "{{ .Values.env.xpraKeycloakClientSecretKey }}"
            - name: XPRA_KEYCLOAK_REDIRECT_URI
              value: "{{ .Values.env.xpraKeycloakRedirectUri }}"
            - name: XPRA_KEYCLOAK_SCOPE
              value: "{{ .Values.env.xpraKeycloakScope }}"
            - name: XPRA_KEYCLOAK_CLAIM_FIELD
              value: "{{ .Values.env.xpraKeycloakClaimField }}"
            - name: XPRA_KEYCLOAK_AUTH_GROUPS
              value: "{{ .Values.env.xpraKeycloakAuthGroups }}"
            - name: XPRA_KEYCLOAK_AUTH_CONDITION
              value: "{{ .Values.env.xpraKeycloakAuthCondition }}"
            - name: XPRA_KEYCLOAK_GRANT_TYPE
              value: "{{ .Values.env.xpraKeycloakGrantType }}"
          volumeMounts:
            - name: x11-socket
              mountPath: /tmp/.X11-unix
        - name: x11-socket-setup
          image: "alpine/socat:1.8.0.0"
          args:
            - TCP-LISTEN:6080,fork,bind=0.0.0.0
            - UNIX-CONNECT:/tmp/.X11-unix/X80
          ports:
            - name: x11-socket-port
              containerPort: 6080
              protocol: TCP
          volumeMounts:
            - name: x11-socket
              mountPath: /tmp/.X11-unix
      volumes:
        - name: x11-socket
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
