apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workbench.fullname" . }}
  labels:
    {{- include "workbench.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "workbench.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "workbench.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "workbench.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: x11-unix
          emptyDir: {}
      {{- $server := $.Files.Get "server.yaml" | fromYaml }}
      {{- $app := $.Files.Get "app.yaml" | fromYaml }}
      containers:
        - name: {{ $server.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ $server.image.repository }}:{{ $server.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $server.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080 # application port inside container
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CARD
              value: "{{ $server.env.card }}"
            - name: XPRA_KEYCLOAK_AUTH
              value: "{{ $server.env.xpraKeycloakAuth }}"
          volumeMounts:
            - name: x11-unix
              mountPath: /tmp/.X11-unix
        - name: {{ $app.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ $app.image.repository }}:{{ $app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $app.image.pullPolicy }}
          #ports:
          #  - name: http
          #    containerPort: 8080 # application port inside container
          #    protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: APP_NAME
              value: "{{ $app.name }}"
            - name: HIP_USER
              value: "{{ $app.env.hipUser }}"
            - name: CARD
              value: "{{ $app.env.card }}"
            - name: DISPLAY
              value: "{{ $app.env.display }}"
          volumeMounts:
            - name: x11-unix
              mountPath: /tmp/.X11-unix
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
