apiVersion: v1
kind: Service
metadata:
  name: {{ include "workbench.fullname" . }}
  labels:
    {{- include "workbench.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.x11Port }}
      targetPort: {{ .Values.service.x11TargetPort }}
      protocol: TCP
      name: socket
  selector:
    {{- include "workbench.selectorLabels" . | nindent 4 }}
