apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secret
stringData:
  # master and infra realm
  GOOGLE_CLIENT_ID: "my-google-client-id"
  GOOGLE_CLIENT_SECRET: "my-google-client-secret"
  # infra realm only
  ALERTMANAGER_CLIENT_SECRET: "my-alertmanager-secret"
  GRAFANA_CLIENT_SECRET: "my-grafana-secret"
  HARBOR_CLIENT_SECRET: "my-harbor-secret"
  MATOMO_CLIENT_SECRET: "my-matomo-secret"
  PROMETHEUS_CLIENT_SECRET: "my-prometheus-secret"
  # chorus realm only
  CHORUS_CLIENT_SECRET: "my-chorus-client-secret"
type: Opaque
