apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterissuer.name }}
spec:
  acme:
    # The ACME server URL
    server: {{ .Values.clusterissuer.server }}
    # Email address used for ACME registration
    email: {{ .Values.clusterissuer.email }}
    # Name of a secret used to store the account's private key
    privateKeySecretRef:
      name: {{ .Values.clusterissuer.secret }}
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
