---
{{- with .Values.clusterissuer }}
{{- if .enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
  acme:
    # The ACME server URL
    server: {{ .server | default "https://acme-v02.api.letsencrypt.org/directory" | quote }}
    # Email address used for ACME registration
    email: {{ .email | quote }}
    # Name of a secret used to store the account's private key
    privateKeySecretRef:
      name: {{ .secret | default .name | quote }}
    solvers:
    # Enable the HTTP-01 challenge provider
    - http01:
        ingress:
          ingressClassName: nginx
{{- end }}
{{- end }}
