apiVersion: v2
description: A Helm chart for Argo Workflows 
name: argo-workflows
version: 0.0.8
dependencies:
  - name: argo-workflows
    version: 0.41.2
    repository: https://argoproj.github.io/argo-helm
