argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      ingressClassName: ""
      annotations:
        kubernetes.io/ingress.class: caddy
      hosts:
        - argo-cd.gpu1.thehip.app
      paths:
        - /
      pathType: Prefix
      tls: []
