apiVersion: v2
description: Helm chart for the sealed-secrets controller.
name: sealed-secrets
version: 0.0.2
dependencies:
  - name: sealed-secrets
    version: 2.15.4
    repository: https://bitnami-labs.github.io/sealed-secrets
