---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ .Values.alertmanagerConfiguration.name | quote }}
spec:
  route:
    groupBy: ["namespace", "alertname", "severity"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    {{- $webex := .Values.alertmanagerConfiguration.webex }}
    {{- $teams := .Values.alertmanagerConfiguration.teams }}
    {{- if or $webex.enabled $teams.enabled }}
    routes:
      {{- if $webex.enabled }}
      - matchers:
          - matchType: =~
            name: severity
            value: {{ $webex.severity | quote }}
        continue: true
        receiver: {{ $webex.name | quote }}
      {{- end }}
      {{- if $teams.enabled }}
      - matchers:
          - matchType: =~
            name: severity
            value: {{ $teams.severity | quote }}
        continue: true
        receiver: {{ $teams.name | quote }}
      {{- end }}
    {{- end }}
    receiver: "null"
  receivers:
    - name: "null"
    {{- if $webex.enabled }}
    - name: {{ $webex.name | quote }}
      webexConfigs:
        - apiURL: https://webexapis.com/v1/messages
          sendResolved: true
          httpConfig:
            authorization:
              type: Bearer
              credentials:
                {{- $webex.credentials | toYaml | nindent 16 }}
          roomID: {{ $webex.roomID }}
          message: '{{`{{ template "webex.default.message" . }}`}}'
    {{- end }}
    {{- if $teams.enabled }}
    - name: {{ $teams.name | quote }}
      msteamsv2Configs:
        - webhookURL:
            {{- $teams.webhookURL | toYaml | nindent 12 }}
          sendResolved: true
          title: '{{`{{ template "msteamsv2.default.title" . }}`}}'
          text: '{{`{{ template "msteamsv2.default.text" . }}`}}'
    {{- end }}
