{{- range $clusterSecret := .Values.managedSecrets }}
---
apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  {{- $clusterSecret.metadata | toYaml | nindent 2 }}
{{- range $k, $v := $clusterSecret }}
  {{- if ne $k "metadata" }}
{{ $k }}:
  {{- $v | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
