firecrest-web-ui-v2:
  replicas: 1
  loggingLevel: info
  fileUploadLimit: "5242880"
  companyName: "CHORUS TRE"
  appName: "FirecREST Dashboard"
  customLogo: false
  redisActive: "true"
  keycloakRealm: "chorus"

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  # MUST be overridden per environment
  host: "firecrest.chorus-tre.local"
  tls:
    enabled: true
    secretName: firecrest-ui-tls
  backend:
    serviceName: firecrest-web-ui-srv
    servicePort: 3000
