{
 "title": "Trivy Operator Dashboard Custom",
 "description": "This Dashboard is used to visualise the metrics from the security reports of the Trivy Operator",
 "tags": [
  "trivy",
  "trivy operator",
  "security",
  "security scanning",
  "vulnerabilities",
  "exposed secrets",
  "misconfiguration"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Quick Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number and Type of Security Issues",
     "type": "stat",
     "description": "Total number by type of security issues identified in the cluster",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(trivy_image_vulnerabilities)",
       "legendFormat": "Vulnerabilities"
      },
      {
       "expr": "sum(trivy_resource_configaudits)",
       "legendFormat": "Misconfiguration"
      },
      {
       "expr": "sum(trivy_image_exposedsecrets)",
       "legendFormat": "Exposed Secrets"
      },
      {
       "expr": "sum(trivy_clusterrole_clusterrbacassessments)",
       "legendFormat": "RBAC Assessment"
      }
     ]
    }
   ]
  },
  { "title": "Vulnerabilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Severity Breakdown of all Vulnerabilities",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Critical\"})",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"High\"})",
     "legendFormat": "High"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Medium\"})",
     "legendFormat": "Medium"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Low\"})",
     "legendFormat": "Low"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Unknown\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Number of Vulnerabilities by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vulnerability by Image",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Critical\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"High\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Medium\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Low\"}) by (image_repository,image_tag)"
    },
    {
     "expr": "sum(trivy_image_vulnerabilities{severity=\"Unknown\"}) by (image_repository,image_tag)"
    }
   ]
  },
  {
   "title": "Vulnerability Details",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(trivy_vulnerability_id) by (container_name, image_repository, image_tag, severity, vuln_id, vuln_title, installed_version, fixed_version)"
    }
   ]
  },
  { "title": "Misconfiguration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Severity Breakdown of all Misconfiguration",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_resource_configaudits{severity=\"Critical\"})",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(trivy_resource_configaudits{severity=\"High\"})",
     "legendFormat": "High"
    },
    {
     "expr": "sum(trivy_resource_configaudits{severity=\"Medium\"})",
     "legendFormat": "Medium"
    },
    {
     "expr": "sum(trivy_resource_configaudits{severity=\"Low\"})",
     "legendFormat": "Low"
    }
   ]
  },
  {
   "title": "Config Audit Details",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 57 },
   "targets": [
    { "expr": "trivy_configaudits_info" }
   ]
  },
  { "title": "RBAC Assessment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Severity Breakdown of RBAC Security Issues",
   "type": "stat",
   "description": "Counts each Role misconfiguration separately.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(trivy_role_rbacassessments{severity=\"Critical\"})",
     "legendFormat": "Critical"
    },
    {
     "expr": "sum(trivy_role_rbacassessments{severity=\"High\"})",
     "legendFormat": "High"
    },
    {
     "expr": "sum(trivy_role_rbacassessments{severity=\"Medium\"})",
     "legendFormat": "Medium"
    },
    {
     "expr": "sum(trivy_role_rbacassessments{severity=\"Low\"})",
     "legendFormat": "Low"
    },
    {
     "expr": "sum(trivy_role_rbacassessments{severity=\"UNKNOWN\"})",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "RBAC Details",
   "type": "table",
   "description": "Summary of RBAC risks. May group multiple RBAC misconfigurations under one result. Also, may not provide detailed metadata for every vulnerability found.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 81 },
   "targets": [
    { "expr": "trivy_rbacassessments_info" }
   ]
  },
  { "title": "Exposed Secrets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Exposed Secrets per namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "sum(trivy_image_exposedsecrets) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Secrets Details",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 104 },
   "targets": [
    { "expr": "trivy_exposedsecrets_info" }
   ]
  }
 ]
}