{
 "title": "Venturenox Kubernetes Logs",
 "description": "This dashboard provide following kubernetes log metrics:\r\n-Namespace logs\r\n-Pods logs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {}
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}|~\"$search\"[$__range]))"
    }
   ]
  },
  {
   "title": "Info Type Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}|~\"info\"[$__range]))"
    }
   ]
  },
  {
   "title": "Error Type Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}|~\"error\"[$__range]))"
    }
   ]
  },
  {
   "title": "Warn Type Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}|~\"warn\"[$__range]))"
    }
   ]
  },
  {
   "title": "Bug Type Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}|~\"bug\"[$__range]))"
    }
   ]
  },
  {
   "title": "Stream of Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", container=~\"$container\", pod=~\"$pod\"}|~\"$search\"[20s]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", container=~\"$container\", pod=~\"$pod\"} |~ \"$search\""
    }
   ]
  }
 ]
}