{{- /* One ReferenceGrant per unique target namespace */}}
{{- $namespaces := dict }}
{{- range .Values.routes }}
{{- $_ := set $namespaces .namespace . }}
{{- end }}
{{- range $ns, $_ := $namespaces }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: chorus-gateway
  namespace: {{ $ns }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: {{ $.Values.gateway.namespace }}
  to:
    - group: ""
      kind: Service
{{- end }}
