{{- range .Values.internalTcpRoutes }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ include "chorus-gateway.internalTCPRouteName" . }}
  namespace: {{ $.Values.gateway.namespace }}
  labels:
    {{- include "chorus-gateway.labels" $ | nindent 4 }}
spec:
  parentRefs:
    - name: {{ $.Values.gateway.name }}
      sectionName: tcp-{{ required "gatewayPort is required" .gatewayPort | toString }}
  rules:
    - backendRefs:
        {{- include "chorus-gateway.backendRef" . | nindent 8 }}
{{- end }}
