# Default values for brainstorm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: harbor.build.chorus-tre.local/brainstorm
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

env:
  card: "none"
  app_name: "brainstorm"
  display: "workbench:80"
  # if brainstorm is in another namespace than the workbench, use the following format
  # display: "service.namespace-of-service.svc.cluster.local:80"
