argo-workflows:
  workflow:
    serviceAccount:
      name: "argo-workflow"
  controller:
    workflowNamespaces:
      - workflows
  server:
    #extraArgs:
    #  - --insecure
    ingress:
      enabled: true
      ingressClassName: ""
      annotations:
        kubernetes.io/ingress.class: caddy
      hosts:
        - argo-workflows.horus-build.thehip.app
      paths:
        - /
      pathType: Prefix
      tls: []
