argo-workflows:
  crds:
    install: true
    keep: true

  workflow:
    serviceAccount:
      name: "argo-workflow"

  controller:
    workflowNamespaces:
      - argo

  server:
    authModes:
      - client
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - argo-workflows.build.chorus-tre.local
      paths:
        - /
      pathType: Prefix
      tls:
        - hosts:
          - argo-workflows.build.chorus-tre.local
          secretName: argo-workflows-tls
