argo-workflows:
  workflow:
    serviceAccount:
      name: "argo-workflow"
  controller:
    workflowNamespaces:
      - argo
  server:
    authModes:
      - client
    ingress:
      enabled: true
      ingressClassName: ""
      annotations:
        kubernetes.io/ingress.class: caddy
      hosts:
        - argo-workflows.build.chorus-tre.local
      paths:
        - /
      pathType: Prefix
      tls: []
