docker-registry-ui:
  ui:
    title: "CHORUS OCI registry"
    dockerRegistryUrl: "https://registry.build.chorus-tre.local"
    registrySecured: false
    ingress:
      enabled: true
      host: registry-ui.build.chorus-tre.local
      ingressClassName: ""
      annotations:                                       
        kubernetes.io/ingress.class: caddy
    proxy: false
    useControlCacheHeader: true
    nginxProxyHeaders: [{'Access-Control-Allow-Credentials': '"true"'}, { 'Access-Control-Allow-Origin': 'https://registry.build.chorus-tre.local' }]
