apiVersion: v2
name: prometheus-blackbox-exporter
description: Prometheus exporter for blackbox testing
version: 0.0.2
dependencies:
  - name: prometheus-blackbox-exporter
    version: 8.17.0
    repository: https://prometheus-community.github.io/helm-charts
