name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - charts/**

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: bitdeps/helm-oci-charts-releaser@v0.1.0
        with:
            oci_registry: ghcr.io/chuv-dip
            oci_username: chuv-dip
            oci_password: ${{ secrets.GITHUB_TOKEN }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
            charts_dir: charts
      - name: Update Index
        run: |
          helm repo index .
          git config --global user.email "no-reply@chuv.ch"
          git config --global user.name "CHUV Bot"
          git add index.yaml
          git commit -m "Update chart index"
          git push
