name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - charts/**

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install yq
        env:
          # renovate: datasource=github-releases depName=mikefarah/yq
          YQ_VERSION: v4.47.2
        run: |
          sudo wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
          sudo chmod +x /usr/local/bin/yq
          yq --version

      # Check that e2e test logic is still functional before releasing new versions
      # so as to catch any regressions (< 1 sec test) at CI testing level.
      - name: Run chart e2e unit tests
        run: python3 -m unittest discover -s tests

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: bitdeps/helm-oci-charts-releaser@caedceea2a5ab997c7e5469a999811dbb3d5b070 # v0.1.5
        with:
          oci_registry: oci://harbor.build.chorus-tre.ch/charts
          oci_username: "robot\\$charts+chorus-tre"
          oci_password: ${{ secrets.HARBOR_ROBOT_PASSWORD }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
          skip_gh_release: false
