name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - charts/**

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: bitdeps/helm-oci-charts-releaser@v0.1.2
        with:
            oci_registry: oci://registry.build.chorus-tre.ch/charts
            oci_username: admin
            oci_password: ${{ secrets.REGISTRY_PASSWORD }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
            charts_dir: charts
