apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: juicefs-s3-gateway
  namespace: {{ .Release.Namespace | quote }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: juicefs-s3-gateway
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: backend
